# Generated by Django 5.2.8 on 2025-11-23 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(choices=[('homem', 'Homem'), ('mulher', 'Mulher')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura_m', models.DecimalField(decimal_places=2, max_digits=3)),
                ('cintura_cm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pescoco_cm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quadril_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
    ]
