# Generated by Django 5.2.8 on 2025-11-25 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_avaliacao_classificacao_avaliacao_resultado_gordura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoAlimentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField()),
                ('nome', models.CharField(max_length=100)),
                ('descricao_alimentos', models.TextField(help_text='Liste os alimentos ou suplementos aqui.')),
                ('eh_suplementacao', models.BooleanField(default=False, verbose_name='É Suplementação?')),
                ('plano_alimentar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.planoalimentar')),
            ],
        ),
    ]
