# Generated by Django 5.2.8 on 2025-11-29 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_planoalimentar_refeicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('local', models.CharField(choices=[('academia', 'Academia de Musculação'), ('casa', 'Em Casa (Peso do Corpo/Elásticos)'), ('crossfit', 'Box de CrossFit'), ('ao_ar_livre', 'Ao Ar Livre (Corrida/Parque)')], default='academia', max_length=20)),
                ('dias_semana', models.CharField(blank=True, max_length=100)),
                ('observacoes', models.TextField(blank=True, help_text='Ex: Aquecer 10min na esteira antes.', null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('series', models.IntegerField(default=3)),
                ('repeticoes', models.CharField(max_length=50)),
                ('carga_kg', models.CharField(blank=True, help_text='Carga inicial sugerida', max_length=50, null=True)),
                ('intervalo_segundos', models.IntegerField(default=60, help_text='Tempo de descanso em segundos')),
                ('video_demonstracao', models.URLField(blank=True, help_text='Link do YouTube ensinando o movimento', null=True)),
                ('plano_treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.planotreino')),
            ],
        ),
    ]
