# Generated by Django 5.2.8 on 2025-11-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_planotreino_exercicio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'verbose_name': 'Avaliação Física', 'verbose_name_plural': 'Avaliações Físicas'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='exercicio',
            options={'verbose_name': 'Exercício', 'verbose_name_plural': 'Exercícios'},
        ),
        migrations.AlterModelOptions(
            name='planoalimentar',
            options={'verbose_name': 'Plano Alimentar', 'verbose_name_plural': 'Planos Alimentares'},
        ),
        migrations.AlterModelOptions(
            name='planotreino',
            options={'verbose_name': 'Plano de Treino', 'verbose_name_plural': 'Planos de Treino'},
        ),
        migrations.AlterModelOptions(
            name='refeicao',
            options={'verbose_name': 'Refeição', 'verbose_name_plural': 'Refeições'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Anamnese / Observações'),
        ),
    ]
