# Generated by Django 5.2.8 on 2025-11-30 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_avaliacao_options_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaAnamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_preenchimento', models.DateTimeField(auto_now_add=True)),
                ('ocupacao', models.CharField(max_length=100, verbose_name='Ocupação Profissional')),
                ('rotina_trabalho', models.CharField(choices=[('sedentario', 'Sedentário (maior parte do tempo sentado)'), ('leve', 'Em pé/Movimento leve'), ('pesado', 'Trabalho braçal/Físico pesado'), ('turnos', 'Trabalho em turnos noturnos ou escalas irregulares')], max_length=20)),
                ('composicao_familiar', models.CharField(max_length=200, verbose_name='Com quem mora')),
                ('responsavel_compras', models.CharField(max_length=50, verbose_name='Responsável pelas compras/preparo')),
                ('problema_cardiaco', models.BooleanField(default=False, verbose_name='Médico disse que tem problema cardíaco?')),
                ('dor_peito_atividade', models.BooleanField(default=False, verbose_name='Sente dor no peito ao treinar?')),
                ('dor_peito_repouso', models.BooleanField(default=False, verbose_name='Sente dor no peito em repouso?')),
                ('tontura_perda_consciencia', models.BooleanField(default=False, verbose_name='Teve tontura ou desmaio recentemente?')),
                ('problema_osseo', models.BooleanField(default=False, verbose_name='Tem problema ósseo/articular?')),
                ('medicamento_pressao', models.BooleanField(default=False, verbose_name='Toma remédio de pressão/coração?')),
                ('historico_lesoes', models.TextField(blank=True, verbose_name='Histórico de Lesões/Cirurgias')),
                ('horas_sono', models.IntegerField(verbose_name='Horas de sono (média)')),
                ('qualidade_sono', models.CharField(choices=[('muito_ruim', 'Muito Ruim'), ('ruim', 'Ruim'), ('boa', 'Boa'), ('muito_boa', 'Muito Boa')], max_length=20)),
                ('ronca_apneia', models.BooleanField(default=False, verbose_name='Ronca ou tem apneia?')),
                ('higiene_sono_telas', models.BooleanField(default=False, verbose_name='Usa telas antes de dormir?')),
                ('objetivo', models.CharField(choices=[('emagrecimento', 'Emagrecimento'), ('hipertrofia', 'Hipertrofia'), ('performance', 'Performance'), ('saude', 'Saúde')], max_length=50)),
                ('efeito_sanfona', models.BooleanField(default=False, verbose_name='Peso oscilou >5kg nos últimos 2 anos?')),
                ('dietas_previas', models.TextField(blank=True, verbose_name='Estratégias/Dietas já tentadas')),
                ('consumo_agua', models.CharField(choices=[('menos_1l', 'Menos de 1L'), ('1_2l', '1 a 2 Litros'), ('mais_2l', 'Mais de 2 Litros')], max_length=20)),
                ('intestino_preso', models.BooleanField(default=False, verbose_name='Intestino preso/Constipação')),
                ('gases_estufamento', models.BooleanField(default=False, verbose_name='Gases/Estufamento excessivo')),
                ('azia_refluxo', models.BooleanField(default=False, verbose_name='Azia/Refluxo frequente')),
                ('suplementos_farmacos', models.TextField(blank=True, verbose_name='Suplementos e Remédios em uso')),
                ('fadiga_matinal', models.BooleanField(default=False, verbose_name='Fadiga ao acordar')),
                ('queda_energia_tarde', models.BooleanField(default=False, verbose_name='Queda de energia à tarde')),
                ('intolerancia_frio', models.BooleanField(default=False, verbose_name='Sente muito frio')),
                ('queda_cabelo', models.BooleanField(default=False, verbose_name='Queda de cabelo/unhas fracas')),
                ('tontura_levantar', models.BooleanField(default=False, verbose_name='Tontura ao levantar rápido')),
                ('desejo_sal_doce', models.BooleanField(default=False, verbose_name='Desejo por sal/doces')),
                ('libido_baixa', models.BooleanField(default=False, verbose_name='H: Libido baixa')),
                ('forca_reduzida', models.BooleanField(default=False, verbose_name='H: Força reduzida')),
                ('tristeza_frequente', models.BooleanField(default=False, verbose_name='H: Tristeza/Rabugice')),
                ('ciclo_menstrual_regular', models.BooleanField(default=True, verbose_name='M: Ciclo Regular')),
                ('amenorreia', models.BooleanField(default=False, verbose_name='M: Ficou sem menstruar (>3 meses)')),
                ('anticoncepcional', models.CharField(blank=True, max_length=100, verbose_name='M: Método Contraceptivo')),
                ('motivacao_principal', models.CharField(max_length=50, verbose_name='Maior Motivação')),
                ('ansiedade', models.BooleanField(default=False, verbose_name='Ansiedade pré-treino/desafio')),
                ('vergonha_corpo', models.CharField(choices=[('nunca', 'Nunca'), ('as_vezes', 'Às vezes'), ('frequentemente', 'Frequentemente')], max_length=20, verbose_name='Evita exposição por vergonha')),
                ('tempo_treino', models.CharField(choices=[('iniciante', 'Iniciante (<6 meses)'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], max_length=20)),
                ('disponibilidade_treino', models.CharField(max_length=100, verbose_name='Dias e Tempo disponível')),
                ('exercicios_odiados', models.TextField(blank=True, verbose_name='O que odeia treinar')),
                ('observacoes_finais', models.TextField(blank=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anamnese', to='core.cliente')),
            ],
            options={
                'verbose_name': 'Ficha de Anamnese',
                'verbose_name_plural': 'Fichas de Anamnese',
            },
        ),
    ]
