# Generated by Django 5.2.8 on 2025-11-30 17:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fichaanamnese'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichaanamnese',
            name='ansiedade',
        ),
        migrations.RemoveField(
            model_name='fichaanamnese',
            name='tontura_levantar',
        ),
        migrations.RemoveField(
            model_name='fichaanamnese',
            name='tristeza_frequente',
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='altura_m',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Altura (m)'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='cintura_cm',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cintura (cm)'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='pescoco_cm',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Pescoço (cm)'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='peso_kg',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso (Kg)'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='quadril_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Quadril (cm)'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='carga_kg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='intervalo_segundos',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='video_demonstracao',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='amenorreia',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='anticoncepcional',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='azia_refluxo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='ciclo_menstrual_regular',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='composicao_familiar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Com quem mora'),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='consumo_agua',
            field=models.CharField(blank=True, choices=[('menos_1l', '< 1L'), ('1_2l', '1-2L'), ('mais_2l', '> 2L')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='desejo_sal_doce',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='dietas_previas',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='disponibilidade_treino',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='dor_peito_atividade',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='dor_peito_repouso',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='efeito_sanfona',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='exercicios_odiados',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='fadiga_matinal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='forca_reduzida',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='gases_estufamento',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='higiene_sono_telas',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='historico_lesoes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='horas_sono',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='intestino_preso',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='intolerancia_frio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='libido_baixa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='medicamento_pressao',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='motivacao_principal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='objetivo',
            field=models.CharField(blank=True, choices=[('emagrecimento', 'Emagrecimento'), ('hipertrofia', 'Hipertrofia'), ('performance', 'Performance'), ('saude', 'Saúde')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='ocupacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ocupação Profissional'),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='problema_cardiaco',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='problema_osseo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='qualidade_sono',
            field=models.CharField(blank=True, choices=[('muito_ruim', 'Muito Ruim'), ('ruim', 'Ruim'), ('boa', 'Boa'), ('muito_boa', 'Muito Boa')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='queda_cabelo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='queda_energia_tarde',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='responsavel_compras',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Responsável compras'),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='ronca_apneia',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='rotina_trabalho',
            field=models.CharField(blank=True, choices=[('sedentario', 'Sedentário'), ('leve', 'Leve'), ('pesado', 'Pesado'), ('turnos', 'Turnos')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='suplementos_farmacos',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='tempo_treino',
            field=models.CharField(blank=True, choices=[('iniciante', 'Iniciante'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='tontura_perda_consciencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='vergonha_corpo',
            field=models.CharField(blank=True, choices=[('nunca', 'Nunca'), ('as_vezes', 'Às vezes'), ('frequentemente', 'Frequentemente')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='planotreino',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refeicao',
            name='descricao_alimentos',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='ConfiguracaoAnamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_link', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('mostrar_social', models.BooleanField(default=True, verbose_name='Mostrar Contexto Social')),
                ('mostrar_saude', models.BooleanField(default=True, verbose_name='Mostrar Triagem de Saúde')),
                ('mostrar_sono', models.BooleanField(default=True, verbose_name='Mostrar Sono')),
                ('mostrar_nutricao', models.BooleanField(default=True, verbose_name='Mostrar Nutrição')),
                ('mostrar_hormonios', models.BooleanField(default=True, verbose_name='Mostrar Hormônios')),
                ('mostrar_psico', models.BooleanField(default=True, verbose_name='Mostrar Psicologia/Treino')),
                ('profissional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
