# Generated by Django 5.2.8 on 2025-12-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_configuracaoanamnese_options_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='foto_costas',
            field=models.ImageField(blank=True, null=True, upload_to='avaliacoes/', verbose_name='Foto Costas'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='foto_frente',
            field=models.ImageField(blank=True, null=True, upload_to='avaliacoes/', verbose_name='Foto Frente'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='avaliacoes/', verbose_name='Foto Perfil'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, help_text='Apenas números com DDD (ex: 11999999999)', max_length=20, null=True),
        ),
    ]
