# Generated by Django 5.2.8 on 2025-12-09 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_consulta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoanamnese',
            name='mostrar_hormonios',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='configuracaoanamnese',
            name='mostrar_nutricao',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='configuracaoanamnese',
            name='mostrar_psico',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='configuracaoanamnese',
            name='mostrar_saude',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='configuracaoanamnese',
            name='mostrar_social',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='configuracaoanamnese',
            name='mostrar_sono',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='composicao_familiar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='consumo_agua',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='objetivo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='ocupacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='qualidade_sono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='responsavel_compras',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='tempo_treino',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fichaanamnese',
            name='vergonha_corpo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='planotreino',
            name='local',
            field=models.CharField(choices=[('academia', 'Academia de Musculação'), ('casa', 'Em Casa'), ('crossfit', 'Box de CrossFit'), ('ao_ar_livre', 'Ao Ar Livre')], default='academia', max_length=20),
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano', models.CharField(choices=[('gratuito', 'Teste Grátis (7 Dias - Ouro)'), ('bronze', 'Plano Bronze'), ('prata', 'Plano Prata'), ('ouro', 'Plano Ouro')], default='gratuito', max_length=20)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_validade', models.DateTimeField()),
                ('ativo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
